object Versions {

    const val coreKtx = "1.9.0"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.8.0"
    const val composeBom = "2023.03.00"
    const val navigationCompose = "2.7.4"
    const val jUnit = "4.13.2"
    const val testExtJUnit = "1.1.5"
    const val testEspressoCore = "3.5.1"
    const val hilt = "2.48"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val croutines = "1.7.3"
    const val splashScreen = "1.0.1"
    const val coil = "2.2.0"

}